parameters:
    
services:
    upper:
      class: Admin\DashboardBundle\Twig\Extension\OccupationExtension
      tags:
        - { name: twig.extension }
    expedia:
        class: Front\GlobalBundle\Services\Expedia
        arguments: 
            - @session
            - @request
            - @security.context
            - @doctrine.orm.entity_manager
            - %url%
            - %urlHotel%
            - %urlReservation%
            - %minorRev%
            - %cid%
            - %apiKey%
            - %customerUserAgent%
            - %supplierCacheTolerance%
            - %supplierType%
            - %creditCardType%
            - %creditCardNumber%
            - %creditCardIdentifier%
            - %creditCardExpirationMonth%
            - %creditCardExpirationYear%
        scope:     request
    devise:
        class: Front\GlobalBundle\Services\Devise
        